# Generated by Django 4.0.4 on 2022-05-10 07:36

from django.db import migrations


def add_models(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Author = apps.get_model('books', 'Author')
    Book = apps.get_model('books', 'Book')
    Library = apps.get_model('books', 'Library')

    author_victor_hugo = Author.objects.create(fullname="Victor Hugo", gender="M")
    author_jk = Author.objects.create(fullname="J.K. Rowling", gender="F")

    hp_books = {"genre": "Fantastic", "author": author_jk}

    Book.objects.bulk_create([
        # JK Rowling
        Book(title="Harry Potter and the Philosopher's Stone", **hp_books),
        Book(title="Harry Potter and the Chamber of Secrets", **hp_books),
        Book(title="Harry Potter and the Prisoner of Azkaban", **hp_books),
        Book(title="Harry Potter and the Goblet of Fire", **hp_books),
        Book(title="Harry Potter and the Order of the Phoenix", **hp_books),
        Book(title="Harry Potter and the Half-Blood Prince", **hp_books),
        Book(title="Harry Potter and the Deathly Hallows", **hp_books),

        # Victor Hugo
        Book(title="The Hunchback of Notre-Dame", genre="Romanticism", author=author_victor_hugo),
        Book(title="Les Misérables", genre="Tragedy", author=author_victor_hugo),
        Book(title="Ruy Blas", genre="tragedy", author=author_victor_hugo),

    ])

    Library.objects.bulk_create([
        Library(name="Library François-Mitterrand", country="FR"),
        Library(name="Library Valeyre", country="FR"),
        Library(name="Library Drouot", country="FR"),
        Library(name="LIBRARY OF CONGRESS", country="USA"),
        Library(name="BODLEIAN LIBRARY", country="UK"),
        Library(name="READING ROOM AT THE BRITISH MUSEUM", country="UK"),
        Library(name="VATICAN LIBRARY", country="IT"),
        Library(name="NATIONAL LIBRARY OF ST. MARK'S", country="IT"),
        Library(name="LIBRARY OF PARLIAMENT", country="CA"),
        Library(name="THOMAS FISHER RARE BOOK LIBRARY", country="CA"),
    ]
    )


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_models, migrations.RunPython.noop)
    ]
